### PR TITLE
proot: persistent chown using xattrs

### PR DESCRIPTION
**Pull request by AkihiroSuda**
following xattrs are used for storing decimal uid/gid strings:

- user.rootlesscontainers.uid
- user.rootlesscontainers.gid

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> user.rootlesscontainers.uid
> user.rootlesscontainers.gid

@cyphar ( https://rootlesscontaine.rs maintainer)

May I use this "rootlesscontainers" identifier here?

@dmcgowan @tonistiigi

I'm planning to implement these uid/gid xattr support in containerd differ, so that containerd & buildkit can manage filesystems without root privilege.
Feedbacks are welcome.

**Comment by cyphar** [comment]
> May I use this "rootlesscontainers" identifier here?

Sure. I actually like this idea so much (and I wish I'd thought of it :smile_cat:) that I might end up updating https://github.com/cyphar/remainroot to use it.

**Comment by cyphar** [comment]
> May I use this "rootlesscontainers" identifier here?

Sure. I actually like this idea so much (and I wish I'd thought of it :smile_cat:) that I might end up updating https://github.com/cyphar/remainroot to use it. Would you mind adding a short piece of information about the schema for `user.rootlesscontainers.{uid,gid}` in the page for https://rootlesscontaine.rs/ so that other users could interoperate with it?

**Comment by AkihiroSuda** [comment]
sure, https://github.com/cyphar/rootlesscontaine.rs/pull/4

**Pull request merged**
